
INSERT INTO public.categories (name, slug, description, sort_order, is_active)
VALUES ('Vastu Items', 'vastu-items', 'Sacred Vastu remedies, yantras, pyramids and energy tools for home & workplace harmony', 50, true)
ON CONFLICT (slug) DO NOTHING;

WITH cat AS (SELECT id FROM public.categories WHERE slug = 'vastu-items')
INSERT INTO public.products (name, slug, subtitle, description, price, mrp, currency, category, category_id, rating, reviews_count, badge, benefits, spiritual_meaning, stock, is_active)
SELECT p.name, p.slug, p.subtitle, p.description, p.price, p.mrp, '₹', 'Vastu Items', cat.id, 4.7, 50, p.badge, p.benefits, p.meaning, 25, true
FROM cat, (VALUES
  ('Vastu Tape', 'vastu-tape', 'Copper Vastu Correction Tape', 'Pure copper tape for correcting Vastu defects in walls and corners.', 299::numeric, 499::numeric, NULL::text, ARRAY['Corrects Vastu defects','Easy to apply','Pure copper'], 'Copper conducts positive energy and neutralizes negative vibrations.'),
  ('Three Legged Frog With Coin', 'three-legged-frog-coin', 'Wealth Attractor', 'Feng Shui three-legged frog holding a coin — symbol of prosperity.', 449, 799, 'Bestseller', ARRAY['Attracts wealth','Brings prosperity','Business growth'], 'The three-legged toad is a powerful Feng Shui wealth symbol.'),
  ('Copper Swastik Pyramid', 'copper-swastik-pyramid', 'Sacred Energy Pyramid', 'Pure copper pyramid engraved with sacred Swastik symbol.', 599, 999, NULL, ARRAY['Removes negativity','Enhances prosperity','Sacred geometry'], 'Swastik is an ancient symbol of auspiciousness and well-being.'),
  ('Lucky Brass Hanging', 'lucky-brass-hanging', 'Auspicious Door Hanging', 'Decorative brass hanging for main door — invites good luck.', 549, 899, NULL, ARRAY['Brings luck','Wards off negativity','Decorative'], 'Brass symbolizes purity and attracts divine blessings.'),
  ('Kuber Yantra', 'kuber-yantra', 'God of Wealth Yantra', 'Sacred Kuber Yantra energized with Vedic mantras for wealth.', 399, 699, 'Sacred', ARRAY['Attracts wealth','Financial stability','Career growth'], 'Kuber is the treasurer of the gods, blessing devotees with abundance.'),
  ('Shree Yantra', 'shree-yantra', 'Mother of All Yantras', 'Sacred Shree Yantra — the most powerful yantra of Goddess Lakshmi.', 499, 899, 'Sacred', ARRAY['Attracts prosperity','Spiritual growth','Removes obstacles'], 'Shree Yantra is the geometric form of Goddess Mahalakshmi.'),
  ('Bells And Coins', 'bells-and-coins', 'Vastu Door Bells', 'Set of brass bells with lucky coins for entrance.', 349, 599, NULL, ARRAY['Sound cleansing','Wards off evil','Decorative'], 'The sound of bells purifies the surrounding energy.'),
  ('Brass Elephant Pair', 'brass-elephant-pair', 'Pair of Wisdom', 'Pair of brass elephants — symbols of strength and good fortune.', 799, 1299, NULL, ARRAY['Brings strength','Protection','Wisdom'], 'Elephants symbolize wisdom, strength and royal power in Vastu.'),
  ('Helix Vastu Dosh Nivaran', 'helix-vastu-dosh-nivaran', 'Vastu Defect Remedy', 'Spiral helix tool to neutralize Vastu defects in any space.', 699, 1199, 'Popular', ARRAY['Removes Vastu dosh','Neutralizes negativity','Easy installation'], 'The helix shape disperses negative energy through its spiral form.'),
  ('Copper Vastu Helix', 'copper-vastu-helix', 'Pure Copper Helix', 'Hand-twisted copper helix for Vastu correction.', 599, 999, NULL, ARRAY['Energy correction','Pure copper','Long lasting'], 'Copper helix channels prana through its spiral form.'),
  ('Brass Helix', 'brass-helix', 'Brass Vastu Helix', 'Pure brass helix for Vastu remediation.', 549, 899, NULL, ARRAY['Vastu correction','Durable brass','Energy flow'], 'Brass amplifies the cleansing power of the helix.'),
  ('Copper Vastu Strip', 'copper-vastu-strip', 'Copper Remedy Strip', 'Pure copper strip for fixing on walls to correct Vastu defects.', 249, 449, NULL, ARRAY['Wall remedy','Pure copper','Easy fix'], 'Copper strips neutralize geopathic stress in walls.'),
  ('Brass Vastu Strip', 'brass-vastu-strip', 'Brass Remedy Strip', 'Pure brass strip for Vastu corrections.', 229, 399, NULL, ARRAY['Vastu fix','Durable','Affordable'], 'Brass strips ground excess energy.'),
  ('Aluminium Vastu Strip', 'aluminium-vastu-strip', 'Aluminium Remedy Strip', 'Lightweight aluminium strip for specific Vastu corrections.', 199, 349, NULL, ARRAY['Light weight','Vastu correction','Affordable'], 'Aluminium reflects negative energy effectively.'),
  ('Mahavastu Remedies Metal Strips', 'mahavastu-metal-strips', 'Multi-Metal Strip Set', 'Set of multi-metal strips for advanced Mahavastu remedies.', 899, 1499, NULL, ARRAY['Complete kit','Mahavastu approved','Multi-metal'], 'Combination of metals balances all five elements.'),
  ('Pure Brass Strip Vastu Remedy', 'pure-brass-strip-remedy', 'Premium Brass Strip', 'Premium grade pure brass strip for Vastu remedy.', 399, 699, NULL, ARRAY['Premium quality','Pure brass','Long lasting'], 'High-grade brass offers superior energy correction.'),
  ('Black Horse Shoe', 'black-horse-shoe', 'Protective Horse Shoe', 'Genuine black iron horse shoe for protection.', 299, 499, NULL, ARRAY['Protection','Wards off evil','Traditional'], 'The horseshoe is a powerful talisman against negative energy.'),
  ('Nazar Battu', 'nazar-battu', 'Evil Eye Protector', 'Traditional Nazar Battu hanging to protect from evil eye.', 199, 349, 'Popular', ARRAY['Evil eye protection','Decorative','Traditional'], 'Nazar Battu absorbs the evil gaze before it reaches you.'),
  ('Brass Sun', 'brass-sun', 'Surya Vastu Symbol', 'Decorative brass sun for energy and vitality.', 449, 799, NULL, ARRAY['Brings energy','Vitality','Decorative'], 'The Sun symbolizes vitality, success and leadership.'),
  ('Wind Chimes', 'wind-chimes', 'Metal Wind Chimes', '6-rod metallic wind chimes for positive Feng Shui.', 549, 899, 'Bestseller', ARRAY['Positive vibrations','Sound therapy','Feng Shui'], 'Wind chimes break negative energy with melodious sound.'),
  ('Feng Shui Crystal Pyramid', 'feng-shui-crystal-pyramid', 'Clear Crystal Pyramid', 'Faceted clear crystal pyramid for energy amplification.', 699, 1199, NULL, ARRAY['Amplifies energy','Decorative','Crystal healing'], 'Crystal pyramids focus and amplify positive energy.'),
  ('Copper Pyramid', 'copper-pyramid', 'Pure Copper Pyramid', 'Pure copper pyramid for Vastu energy correction.', 599, 999, NULL, ARRAY['Energy correction','Pure copper','Vastu remedy'], 'Copper pyramid balances all five elements.'),
  ('Study Pyramid', 'study-pyramid', 'Concentration Pyramid', 'Special pyramid designed for study tables to boost focus.', 499, 899, 'New', ARRAY['Boosts concentration','Improves memory','Study aid'], 'Pyramid energy enhances mental clarity and focus.'),
  ('Swastik Symbol', 'swastik-symbol', 'Sacred Swastik Plaque', 'Decorative Swastik symbol for entrance.', 299, 499, NULL, ARRAY['Auspicious','Removes negativity','Sacred symbol'], 'Swastik invites the four-fold blessings of Lord Ganesha.'),
  ('Om Symbol', 'om-symbol', 'Sacred Om Plaque', 'Decorative Om symbol for home and temple.', 299, 499, NULL, ARRAY['Sacred sound','Peace','Spirituality'], 'Om is the primordial sound of the universe.'),
  ('Door Hanging Coins', 'door-hanging-coins', 'Lucky Coin Hanging', 'Set of Chinese lucky coins tied with red thread.', 249, 399, NULL, ARRAY['Attracts wealth','Door remedy','Feng Shui'], 'Chinese coins invite continuous flow of wealth.'),
  ('Bagua Mirror Vastu', 'bagua-mirror-vastu', 'Feng Shui Bagua Mirror', 'Octagonal Bagua mirror for protection from negative energy.', 449, 799, NULL, ARRAY['Reflects negativity','Feng Shui','Protection'], 'Bagua mirror deflects sha chi away from your home.'),
  ('Pakua Mirror', 'pakua-mirror', 'Convex Pakua Mirror', 'Convex Pakua mirror to disperse negative energy.', 449, 799, NULL, ARRAY['Disperses negativity','Protection','Feng Shui'], 'Pakua mirror scatters harmful energy in all directions.'),
  ('Vastu Purush Copper', 'vastu-purush-copper', 'Copper Vastu Purush', 'Pure copper Vastu Purush plate for foundation laying.', 1299, 1999, 'Sacred', ARRAY['Foundation blessing','Vastu remedy','Pure copper'], 'Vastu Purush is the deity of every building site.'),
  ('7 Horse Pyrite Frame', '7-horse-pyrite-frame', 'Running Horses Pyrite', 'Framed 7 running horses with pyrite stones for success.', 999, 1599, 'Popular', ARRAY['Success','Career growth','Decorative'], '7 running horses symbolize unstoppable progress and victory.'),
  ('Peacock Pyrite Frame', 'peacock-pyrite-frame', 'Beautiful Peacock Frame', 'Framed peacock art embedded with pyrite for beauty and abundance.', 899, 1499, NULL, ARRAY['Beauty','Abundance','Decorative'], 'The peacock represents beauty, integrity and abundance.'),
  ('Evil Eye Frame', 'evil-eye-frame', 'Protection Wall Frame', 'Decorative wall frame for evil eye protection.', 799, 1299, NULL, ARRAY['Evil eye protection','Wall decor','Energy shield'], 'The framed evil eye reflects all malicious gazes.'),
  ('Kirtimukhi Frame', 'kirtimukhi-frame', 'Glory Face Frame', 'Sacred Kirtimukhi frame for entrance protection.', 899, 1499, NULL, ARRAY['Entrance protection','Sacred','Removes obstacles'], 'Kirtimukhi (Face of Glory) devours negativity at thresholds.'),
  ('Kaal Bhairavi Frame', 'kaal-bhairavi-frame', 'Goddess Frame', 'Sacred frame of Goddess Kaal Bhairavi for protection.', 999, 1599, 'Sacred', ARRAY['Divine protection','Removes fear','Sacred'], 'Goddess Kaal Bhairavi protects from all negative forces.'),
  ('7 Horse Frame', '7-horse-frame', 'Seven Horses Frame', 'Classic 7 running horses framed art for success.', 799, 1299, NULL, ARRAY['Success','Progress','Decorative'], '7 horses are a Vastu symbol of unstoppable success.'),
  ('Money Tree Frame', 'money-tree-frame', 'Wealth Tree Frame', 'Framed money tree art with crystals for prosperity.', 999, 1599, 'Bestseller', ARRAY['Attracts wealth','Prosperity','Decorative'], 'Money tree symbolizes growing wealth and abundance.'),
  ('Para Shivling Mercury', 'para-shivling-mercury', 'Solid Mercury Shivling', 'Rare solid mercury (Parad) Shivling — most sacred form.', 4999, 7999, 'Premium', ARRAY['Highly sacred','Spiritual power','Rare'], 'Parad Shivling holds the energy of Lord Shiva himself.'),
  ('Clear Quartz Shivling Sphatik', 'sphatik-shivling', 'Sacred Crystal Shivling', 'Pure clear quartz (Sphatik) Shivling for worship.', 1999, 2999, 'Sacred', ARRAY['Sacred worship','Purity','Divine energy'], 'Sphatik Shivling is the purest form of Lord Shiva worship.'),
  ('Three Layer Vastu Pyramid', 'three-layer-vastu-pyramid', 'Premium Vastu Pyramid', 'Three layered Vastu pyramid for complete energy correction.', 1499, 2499, 'Premium', ARRAY['Complete remedy','Premium','Powerful'], 'Three layers represent body, mind and spirit alignment.')
) AS p(name, slug, subtitle, description, price, mrp, badge, benefits, meaning);

UPDATE public.products SET image_url = 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&q=80'
WHERE category = 'Vastu Items' AND image_url IS NULL;
